apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-website-deployment
  namespace: homelab
  labels:
    app: personal-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personal-website
  template:
    metadata:
      labels:
        app: personal-website
    spec:
      containers:
      - name: personal-website
        image: lincketheo/personal_website:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: personal-website-service
  namespace: homelab
spec:
  selector:
    app: personal-website
  ports:
    - port: 8080
      targetPort: 80
  type: LoadBalancer
